modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "constellar"
version = "0.1.0"
displayName = "Constellar"
description = '''
Mod tech/magico baseado em constelacoes, com energia Forcefield (FD) e multiblocos.
'''

[[dependencies.constellar]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.constellar]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
